# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wigwam < Formula
  desc "Access tmux sessions from the browser"
  homepage "https://github.com/Vennify/wigwam-releases"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.1.0/wigwam_0.1.0_darwin_amd64.tar.gz"
      sha256 "8d7b9f6afff92be29c8bd5b4c8293d078c519fa68ff7808349b4cf5a6afef55d"

      define_method(:install) do
        bin.install "wigwam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.1.0/wigwam_0.1.0_darwin_arm64.tar.gz"
      sha256 "cd913b24a18c168d90a9ff7d656c6a23d80091c3028a3618788e90bf7a789210"

      define_method(:install) do
        bin.install "wigwam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.1.0/wigwam_0.1.0_linux_amd64.tar.gz"
      sha256 "196982de067b19985b341eb4cbc68dda0aa09f34ad1cc11bf6703223eded9efd"
      define_method(:install) do
        bin.install "wigwam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.1.0/wigwam_0.1.0_linux_arm64.tar.gz"
      sha256 "30d0670a6620f1ecb30d635f764c9eeeab02bbdfcdbad1c0adbd5d298bb087ba"
      define_method(:install) do
        bin.install "wigwam"
      end
    end
  end
end
