# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wigwam < Formula
  desc "Access tmux sessions from the browser"
  homepage "https://github.com/Vennify/wigwam-releases"
  version "0.8.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.2/wigwam_0.8.2_darwin_amd64.tar.gz"
      sha256 "bfdd31c4ccc7133f76d14389ec3fe278a06bfb79310e3d8e15e4725cc9cc5854"

      define_method(:install) do
        bin.install "wigwam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.2/wigwam_0.8.2_darwin_arm64.tar.gz"
      sha256 "86a714dc02572cc70591c1b5a1b94fa44767851fb1203190038973664581111f"

      define_method(:install) do
        bin.install "wigwam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.2/wigwam_0.8.2_linux_amd64.tar.gz"
      sha256 "7a4ea618bcecfc929b05777406597b7c4fd3fbf58a2e1c88e1a7e88d840c3c52"
      define_method(:install) do
        bin.install "wigwam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.2/wigwam_0.8.2_linux_arm64.tar.gz"
      sha256 "548546395853c42218a4948a70f991a24a0da3c6bc4d6a3218dd8b27c383df12"
      define_method(:install) do
        bin.install "wigwam"
      end
    end
  end
end
