# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wigwam < Formula
  desc "Access tmux sessions from the browser"
  homepage "https://github.com/Vennify/wigwam-releases"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.1/wigwam_0.8.1_darwin_amd64.tar.gz"
      sha256 "400a5d33349dd21023f9972575e75cbc90f3354b7a48b09fbba0dd12417141c3"

      define_method(:install) do
        bin.install "wigwam"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.1/wigwam_0.8.1_darwin_arm64.tar.gz"
      sha256 "d41264a093d2a7002934c386d65aa88e9844259febd58e05b1049f804a89bd40"

      define_method(:install) do
        bin.install "wigwam"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.1/wigwam_0.8.1_linux_amd64.tar.gz"
      sha256 "0bf777a511f80a3893ae08588dd5722eef370b4a4d4b25fac56ae7d06421cca6"
      define_method(:install) do
        bin.install "wigwam"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Vennify/wigwam-releases/releases/download/v0.8.1/wigwam_0.8.1_linux_arm64.tar.gz"
      sha256 "b8eadf63c46614cf7ea1e58137563e4d134a69211e5f8b112761bea36639d983"
      define_method(:install) do
        bin.install "wigwam"
      end
    end
  end
end
