# This file was generated by GoReleaser. DO NOT EDIT.
cask "wigwam" do
  name "wigwam"
  desc "Access tmux sessions from the browser"
  homepage "https://github.com/Vennify/wigwam-releases"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wigwam"

  on_macos do
    on_intel do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_darwin_amd64.tar.gz"
      sha256 "400889616c5c828a073d80b8dde1e2e905e698736d9e8b4486003cceb405d109"
    end
    on_arm do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_darwin_arm64.tar.gz"
      sha256 "b1786bd2abe3fc7edd7b36e1fd7044f7c23c66924e9872dff2cea3f363e5f11d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_linux_amd64.tar.gz"
      sha256 "3ba7c780241eac3dafbc51ae51729536b1702aa49f70a1230ad7ae8fe1ebf7f4"
    end
    on_arm do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_linux_arm64.tar.gz"
      sha256 "7ddcd5c6f1c2aa51486dc02e8c8ae60bd573d83cd230965cf4a126bafa12f657"
    end
  end

  # No zap stanza required
end
