# This file was generated by GoReleaser. DO NOT EDIT.
cask "wigwam" do
  name "wigwam"
  desc "Access tmux sessions from the browser"
  homepage "https://github.com/Vennify/wigwam-releases"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wigwam"

  on_macos do
    on_intel do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_darwin_amd64.tar.gz"
      sha256 "6f9c01b111c676971081f657ca9d555d827a218a2327122bbbca907e606ad6f0"
    end
    on_arm do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_darwin_arm64.tar.gz"
      sha256 "32f2628a428d0ed5021db5aadcd2f5b71bb8b1df38ba91f7352fda645a464aa3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_linux_amd64.tar.gz"
      sha256 "e7a6bdf5f08468aa6ee8c3fd80691ac5ca1a66dbfe7bef2b816ea12e17f721a0"
    end
    on_arm do
      url "https://github.com/Vennify/wigwam-releases/releases/download/v#{version}/wigwam_#{version}_linux_arm64.tar.gz"
      sha256 "11192dd801da3411c77b6902f93b92dce57af613eeb0a2a88f27441148be648c"
    end
  end

  # No zap stanza required
end
